on:
  push
jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Behave
        run: |
          pip install behave  # Installs the Behave framework

      - name: Run Flask app
        run: |
          nohup python app.py &  # Run Flask app in background (assumes 'app.py' is your Flask app)

      - name: Wait for API to be available
        run: |
          until curl --silent --output /dev/null http://localhost:8080; do
            echo "Waiting for Flask API to be available..."
            sleep 2
          done
          echo "Flask API is now available!"

      - name: Run Pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q --capture=no

      - name: Run Behave tests
        run: |
          behave

   #   - name: Postman test
   #    uses: matt-ball/newman-action@master
   #     with:
   #      collection: Test Flask app.postman_collection.json
